# Generated by Django 2.2.24 on 2023-07-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20220109_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('iframe', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
